INLINE void kon_abx(void);
INLINE void kon_adca_di(void);
INLINE void kon_adca_ex(void);
INLINE void kon_adca_im(void);
INLINE void kon_adca_ix(void);
INLINE void kon_adcb_di(void);
INLINE void kon_adcb_ex(void);
INLINE void kon_adcb_im(void);
INLINE void kon_adcb_ix(void);
INLINE void kon_adda_di(void);
INLINE void kon_adda_ex(void);
INLINE void kon_adda_im(void);
INLINE void kon_adda_ix(void);
INLINE void kon_addb_di(void);
INLINE void kon_addb_ex(void);
INLINE void kon_addb_im(void);
INLINE void kon_addb_ix(void);
INLINE void kon_addd_di(void);
INLINE void kon_addd_ex(void);
INLINE void kon_addd_im(void);
INLINE void kon_addd_ix(void);
INLINE void kon_anda_di(void);
INLINE void kon_anda_ex(void);
INLINE void kon_anda_im(void);
INLINE void kon_anda_ix(void);
INLINE void kon_andb_di(void);
INLINE void kon_andb_ex(void);
INLINE void kon_andb_im(void);
INLINE void kon_andb_ix(void);
INLINE void kon_andcc(void);
INLINE void kon_asl_di(void);
INLINE void kon_asl_ex(void);
INLINE void kon_asl_ix(void);
INLINE void kon_asla(void);
INLINE void kon_aslb(void);
INLINE void kon_asr_di(void);
INLINE void kon_asr_ex(void);
INLINE void kon_asr_ix(void);
INLINE void kon_asra(void);
INLINE void kon_asrb(void);
INLINE void kon_bcc(void);
INLINE void kon_bcs(void);
INLINE void kon_beq(void);
INLINE void kon_bge(void);
INLINE void kon_bgt(void);
INLINE void kon_bhi(void);
INLINE void kon_bita_di(void);
INLINE void kon_bita_ex(void);
INLINE void kon_bita_im(void);
INLINE void kon_bita_ix(void);
INLINE void kon_bitb_di(void);
INLINE void kon_bitb_ex(void);
INLINE void kon_bitb_im(void);
INLINE void kon_bitb_ix(void);
INLINE void kon_ble(void);
INLINE void kon_bls(void);
INLINE void kon_blt(void);
INLINE void kon_bmi(void);
INLINE void kon_bne(void);
INLINE void kon_bpl(void);
INLINE void kon_bra(void);
INLINE void kon_brn(void);
INLINE void kon_bsr(void);
INLINE void kon_bvc(void);
INLINE void kon_bvs(void);
INLINE void kon_clr_di(void);
INLINE void kon_clr_ex(void);
INLINE void kon_clr_ix(void);
INLINE void kon_clra(void);
INLINE void kon_clrb(void);
INLINE void kon_cmpa_di(void);
INLINE void kon_cmpa_ex(void);
INLINE void kon_cmpa_im(void);
INLINE void kon_cmpa_ix(void);
INLINE void kon_cmpb_di(void);
INLINE void kon_cmpb_ex(void);
INLINE void kon_cmpb_im(void);
INLINE void kon_cmpb_ix(void);
INLINE void kon_cmpd_di(void);
INLINE void kon_cmpd_ex(void);
INLINE void kon_cmpd_im(void);
INLINE void kon_cmpd_ix(void);
INLINE void kon_cmps_di(void);
INLINE void kon_cmps_ex(void);
INLINE void kon_cmps_im(void);
INLINE void kon_cmps_ix(void);
INLINE void kon_cmpu_di(void);
INLINE void kon_cmpu_ex(void);
INLINE void kon_cmpu_im(void);
INLINE void kon_cmpu_ix(void);
INLINE void kon_cmpx_di(void);
INLINE void kon_cmpx_ex(void);
INLINE void kon_cmpx_im(void);
INLINE void kon_cmpx_ix(void);
INLINE void kon_cmpy_di(void);
INLINE void kon_cmpy_ex(void);
INLINE void kon_cmpy_im(void);
INLINE void kon_cmpy_ix(void);
INLINE void kon_com_di(void);
INLINE void kon_com_ex(void);
INLINE void kon_com_ix(void);
INLINE void kon_coma(void);
INLINE void kon_comb(void);
INLINE void kon_cwai(void);
INLINE void kon_daa(void);
INLINE void kon_dec_di(void);
INLINE void kon_dec_ex(void);
INLINE void kon_dec_ix(void);
INLINE void kon_deca(void);
INLINE void kon_decb(void);
INLINE void kon_eora_di(void);
INLINE void kon_eora_ex(void);
INLINE void kon_eora_im(void);
INLINE void kon_eora_ix(void);
INLINE void kon_eorb_di(void);
INLINE void kon_eorb_ex(void);
INLINE void kon_eorb_im(void);
INLINE void kon_eorb_ix(void);
INLINE void kon_exg(void);
INLINE void kon_illegal(void);
INLINE void kon_inc_di(void);
INLINE void kon_inc_ex(void);
INLINE void kon_inc_ix(void);
INLINE void kon_inca(void);
INLINE void kon_incb(void);
INLINE void kon_jmp_di(void);
INLINE void kon_jmp_ex(void);
INLINE void kon_jmp_ix(void);
INLINE void kon_jsr_di(void);
INLINE void kon_jsr_ex(void);
INLINE void kon_jsr_ix(void);
INLINE void kon_lbcc(void);
INLINE void kon_lbcs(void);
INLINE void kon_lbeq(void);
INLINE void kon_lbge(void);
INLINE void kon_lbgt(void);
INLINE void kon_lbhi(void);
INLINE void kon_lble(void);
INLINE void kon_lbls(void);
INLINE void kon_lblt(void);
INLINE void kon_lbmi(void);
INLINE void kon_lbne(void);
INLINE void kon_lbpl(void);
INLINE void kon_lbra(void);
INLINE void kon_lbrn(void);
INLINE void kon_lbsr(void);
INLINE void kon_lbvc(void);
INLINE void kon_lbvs(void);
INLINE void kon_lda_di(void);
INLINE void kon_lda_ex(void);
INLINE void kon_lda_im(void);
INLINE void kon_lda_ix(void);
INLINE void kon_ldb_di(void);
INLINE void kon_ldb_ex(void);
INLINE void kon_ldb_im(void);
INLINE void kon_ldb_ix(void);
INLINE void kon_ldd_di(void);
INLINE void kon_ldd_ex(void);
INLINE void kon_ldd_im(void);
INLINE void kon_ldd_ix(void);
INLINE void kon_lds_di(void);
INLINE void kon_lds_ex(void);
INLINE void kon_lds_im(void);
INLINE void kon_lds_ix(void);
INLINE void kon_ldu_di(void);
INLINE void kon_ldu_ex(void);
INLINE void kon_ldu_im(void);
INLINE void kon_ldu_ix(void);
INLINE void kon_ldx_di(void);
INLINE void kon_ldx_ex(void);
INLINE void kon_ldx_im(void);
INLINE void kon_ldx_ix(void);
INLINE void kon_ldy_di(void);
INLINE void kon_ldy_ex(void);
INLINE void kon_ldy_im(void);
INLINE void kon_ldy_ix(void);
INLINE void kon_leas(void);
INLINE void kon_leau(void);
INLINE void kon_leax(void);
INLINE void kon_leay(void);
INLINE void kon_lsr_di(void);
INLINE void kon_lsr_ex(void);
INLINE void kon_lsr_ix(void);
INLINE void kon_lsra(void);
INLINE void kon_lsrb(void);
INLINE void kon_mul(void);
INLINE void kon_neg_di(void);
INLINE void kon_neg_ex(void);
INLINE void kon_neg_ix(void);
INLINE void kon_nega(void);
INLINE void kon_negb(void);
INLINE void kon_nop(void);
INLINE void kon_ora_di(void);
INLINE void kon_ora_ex(void);
INLINE void kon_ora_im(void);
INLINE void kon_ora_ix(void);
INLINE void kon_orb_di(void);
INLINE void kon_orb_ex(void);
INLINE void kon_orb_im(void);
INLINE void kon_orb_ix(void);
INLINE void kon_orcc(void);
INLINE void kon_pshs(void);
INLINE void kon_pshu(void);
INLINE void kon_puls(void);
INLINE void kon_pulu(void);
INLINE void kon_rol_di(void);
INLINE void kon_rol_ex(void);
INLINE void kon_rol_ix(void);
INLINE void kon_rola(void);
INLINE void kon_rolb(void);
INLINE void kon_ror_di(void);
INLINE void kon_ror_ex(void);
INLINE void kon_ror_ix(void);
INLINE void kon_rora(void);
INLINE void kon_rorb(void);
INLINE void kon_rti(void);
INLINE void kon_rts(void);
INLINE void kon_sbca_di(void);
INLINE void kon_sbca_ex(void);
INLINE void kon_sbca_im(void);
INLINE void kon_sbca_ix(void);
INLINE void kon_sbcb_di(void);
INLINE void kon_sbcb_ex(void);
INLINE void kon_sbcb_im(void);
INLINE void kon_sbcb_ix(void);
INLINE void kon_sex(void);
INLINE void kon_sta_di(void);
INLINE void kon_sta_ex(void);
INLINE void kon_sta_im(void);
INLINE void kon_sta_ix(void);
INLINE void kon_stb_di(void);
INLINE void kon_stb_ex(void);
INLINE void kon_stb_im(void);
INLINE void kon_stb_ix(void);
INLINE void kon_std_di(void);
INLINE void kon_std_ex(void);
INLINE void kon_std_im(void);
INLINE void kon_std_ix(void);
INLINE void kon_sts_di(void);
INLINE void kon_sts_ex(void);
INLINE void kon_sts_im(void);
INLINE void kon_sts_ix(void);
INLINE void kon_stu_di(void);
INLINE void kon_stu_ex(void);
INLINE void kon_stu_im(void);
INLINE void kon_stu_ix(void);
INLINE void kon_stx_di(void);
INLINE void kon_stx_ex(void);
INLINE void kon_stx_im(void);
INLINE void kon_stx_ix(void);
INLINE void kon_sty_di(void);
INLINE void kon_sty_ex(void);
INLINE void kon_sty_im(void);
INLINE void kon_sty_ix(void);
INLINE void kon_suba_di(void);
INLINE void kon_suba_ex(void);
INLINE void kon_suba_im(void);
INLINE void kon_suba_ix(void);
INLINE void kon_subb_di(void);
INLINE void kon_subb_ex(void);
INLINE void kon_subb_im(void);
INLINE void kon_subb_ix(void);
INLINE void kon_subd_di(void);
INLINE void kon_subd_ex(void);
INLINE void kon_subd_im(void);
INLINE void kon_subd_ix(void);
INLINE void kon_swi(void);
INLINE void kon_swi2(void);
INLINE void kon_swi3(void);
INLINE void kon_sync(void);
INLINE void kon_tfr(void);
INLINE void kon_tst_di(void);
INLINE void kon_tst_ex(void);
INLINE void kon_tst_ix(void);
INLINE void kon_tsta(void);
INLINE void kon_tstb(void);

INLINE void kon_clrd(void); /* 6309 */
INLINE void kon_clrw_ix(void); /* 6309 ? */
INLINE void kon_clrw_di(void); /* 6309 ? */
INLINE void kon_clrw_ex(void); /* 6309 ? */
INLINE void kon_negd(void);
INLINE void kon_negw_ix(void); /* 6309 ? */
INLINE void kon_negw_di(void); /* 6309 ? */
INLINE void kon_negw_ex(void); /* 6309 ? */
INLINE void kon_lsrd( void ); /* 6309 */
INLINE void kon_lsrd_di( void ); /* 6309 */
INLINE void kon_lsrd_ix( void ); /* 6309 */
INLINE void kon_lsrd_ex( void ); /* 6309 */
INLINE void kon_rord( void ); /* 6309 ? */
INLINE void kon_rord_di( void ); /* 6309 */
INLINE void kon_rord_ix( void ); /* 6309 */
INLINE void kon_rord_ex( void ); /* 6309 */
INLINE void kon_asrd( void ); /* 6309 ? */
INLINE void kon_asrd_di( void ); /* 6309 */
INLINE void kon_asrd_ix( void ); /* 6309 */
INLINE void kon_asrd_ex( void ); /* 6309 */
INLINE void kon_asld( void ); /* 6309 */
INLINE void kon_asld_di( void ); /* 6309 */
INLINE void kon_asld_ix( void ); /* 6309 */
INLINE void kon_asld_ex( void ); /* 6309 */
INLINE void kon_rold( void ); /* 6309 ? */
INLINE void kon_rold_di( void ); /* 6309 */
INLINE void kon_rold_ix( void ); /* 6309 */
INLINE void kon_rold_ex( void ); /* 6309 */
INLINE void kon_tstd(void);
INLINE void kon_tstw_di( void );
INLINE void kon_tstw_ix( void );
INLINE void kon_tstw_ex( void );

/* Custom opcodes */
INLINE void kon_setline_im( void );
INLINE void kon_setline_ix( void );
INLINE void kon_setline_di( void );
INLINE void kon_setline_ex( void );
INLINE void kon_bmove( void );
INLINE void kon_move( void );
INLINE void kon_decbjnz( void );
INLINE void kon_decxjnz( void );
INLINE void kon_bset( void );
INLINE void kon_bset2( void );
INLINE void kon_lmul(void);
INLINE void kon_divx( void );
INLINE void kon_incd( void );
INLINE void kon_incw_di( void );
INLINE void kon_incw_ix( void );
INLINE void kon_incw_ex( void );
INLINE void kon_decd( void );
INLINE void kon_decw_di( void );
INLINE void kon_decw_ix( void );
INLINE void kon_decw_ex( void );
INLINE void kon_lsrw_di( void );
INLINE void kon_lsrw_ix( void );
INLINE void kon_lsrw_ex( void );
INLINE void kon_rorw_di( void );
INLINE void kon_rorw_ix( void );
INLINE void kon_rorw_ex( void );
INLINE void kon_asrw_di( void );
INLINE void kon_asrw_ix( void );
INLINE void kon_asrw_ex( void );
INLINE void kon_aslw_di( void );
INLINE void kon_aslw_ix( void );
INLINE void kon_aslw_ex( void );
INLINE void kon_rolw_di( void );
INLINE void kon_rolw_ix( void );
INLINE void kon_rolw_ex( void );
INLINE void kon_absa( void );
INLINE void kon_absb( void );
INLINE void kon_absd( void );

INLINE void kon_opcode2( void );

static void (*konami_main[0x100])(void) = {
	kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,	/* 00 */
	kon_opcode2,kon_opcode2,kon_opcode2,kon_opcode2,kon_pshs   ,kon_pshu   ,kon_puls   ,kon_pulu    ,
	kon_lda_im ,kon_ldb_im ,kon_opcode2,kon_opcode2,kon_adda_im,kon_addb_im,kon_opcode2,kon_opcode2,	/* 10 */
	kon_adca_im,kon_adcb_im,kon_opcode2,kon_opcode2,kon_suba_im,kon_subb_im,kon_opcode2,kon_opcode2,
	kon_sbca_im,kon_sbcb_im,kon_opcode2,kon_opcode2,kon_anda_im,kon_andb_im,kon_opcode2,kon_opcode2,	/* 20 */
	kon_bita_im,kon_bitb_im,kon_opcode2,kon_opcode2,kon_eora_im,kon_eorb_im,kon_opcode2,kon_opcode2,
	kon_ora_im ,kon_orb_im ,kon_opcode2,kon_opcode2,kon_cmpa_im,kon_cmpb_im,kon_opcode2,kon_opcode2,	/* 30 */
	kon_setline_im,kon_opcode2,kon_opcode2,kon_opcode2,kon_andcc,kon_orcc  ,kon_exg    ,kon_tfr     ,
	kon_ldd_im ,kon_opcode2,kon_ldx_im ,kon_opcode2,kon_ldy_im ,kon_opcode2,kon_ldu_im ,kon_opcode2,	/* 40 */
	kon_lds_im ,kon_opcode2,kon_cmpd_im,kon_opcode2,kon_cmpx_im,kon_opcode2,kon_cmpy_im,kon_opcode2,
	kon_cmpu_im,kon_opcode2,kon_cmps_im,kon_opcode2,kon_addd_im,kon_opcode2,kon_subd_im,kon_opcode2,	/* 50 */
	kon_opcode2,kon_opcode2,kon_opcode2,kon_opcode2,kon_opcode2,kon_illegal,kon_illegal,kon_illegal,
	kon_bra    ,kon_bhi    ,kon_bcc    ,kon_bne    ,kon_bvc    ,kon_bpl    ,kon_bge    ,kon_bgt    ,	/* 60 */
	kon_lbra   ,kon_lbhi   ,kon_lbcc   ,kon_lbne   ,kon_lbvc   ,kon_lbpl   ,kon_lbge   ,kon_lbgt    ,
	kon_brn    ,kon_bls    ,kon_bcs    ,kon_beq    ,kon_bvs    ,kon_bmi    ,kon_blt    ,kon_ble    , /* 70 */
	kon_lbrn   ,kon_lbls   ,kon_lbcs   ,kon_lbeq   ,kon_lbvs   ,kon_lbmi   ,kon_lblt   ,kon_lble    ,
	kon_clra   ,kon_clrb   ,kon_opcode2,kon_coma   ,kon_comb   ,kon_opcode2,kon_nega   ,kon_negb    ,	/** 80 */
	kon_opcode2,kon_inca   ,kon_incb   ,kon_opcode2,kon_deca   ,kon_decb   ,kon_opcode2,kon_rts     ,
	kon_tsta   ,kon_tstb   ,kon_opcode2,kon_lsra   ,kon_lsrb   ,kon_opcode2,kon_rora   ,kon_rorb    ,	/** 90 */
	kon_opcode2,kon_asra   ,kon_asrb   ,kon_opcode2,kon_asla   ,kon_aslb   ,kon_opcode2,kon_rti     ,
	kon_rola   ,kon_rolb   ,kon_opcode2,kon_opcode2,kon_opcode2,kon_opcode2,kon_opcode2,kon_opcode2,	/* a0 */
	kon_opcode2,kon_opcode2,kon_bsr    ,kon_lbsr   ,kon_decbjnz,kon_decxjnz,kon_nop    ,kon_illegal,
	kon_abx    ,kon_daa	   ,kon_sex    ,kon_mul    ,kon_lmul   ,kon_divx   ,kon_bmove  ,kon_move    ,	/** b0 */
	kon_lsrd   ,kon_opcode2,kon_rord   ,kon_opcode2,kon_asrd   ,kon_opcode2,kon_asld   ,kon_opcode2,
	kon_rold   ,kon_opcode2,kon_clrd   ,kon_opcode2,kon_negd   ,kon_opcode2,kon_incd   ,kon_opcode2,	/* c0 */
	kon_decd   ,kon_opcode2,kon_tstd   ,kon_opcode2,kon_absa   ,kon_absb   ,kon_absd   ,kon_bset    ,
	kon_bset2  ,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,	/* d0 */
	kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,
	kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,	/* e0 */
	kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,
	kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,	/* f0 */
	kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal
};

static void (*konami_indexed[0x100])(void) = {
	kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,	/* 00 */
	kon_leax   ,kon_leay   ,kon_leau   ,kon_leas   ,kon_illegal,kon_illegal,kon_illegal,kon_illegal,
	kon_illegal,kon_illegal,kon_lda_ix ,kon_ldb_ix ,kon_illegal,kon_illegal,kon_adda_ix,kon_addb_ix,	/* 10 */
	kon_illegal,kon_illegal,kon_adca_ix,kon_adcb_ix,kon_illegal,kon_illegal,kon_suba_ix,kon_subb_ix,
	kon_illegal,kon_illegal,kon_sbca_ix,kon_sbcb_ix,kon_illegal,kon_illegal,kon_anda_ix,kon_andb_ix,	/* 20 */
	kon_illegal,kon_illegal,kon_bita_ix,kon_bitb_ix,kon_illegal,kon_illegal,kon_eora_ix,kon_eorb_ix,
	kon_illegal,kon_illegal,kon_ora_ix ,kon_orb_ix ,kon_illegal,kon_illegal,kon_cmpa_ix,kon_cmpb_ix,	/* 30 */
	kon_illegal,kon_setline_ix,kon_sta_ix,kon_stb_ix,kon_illegal,kon_illegal,kon_illegal,kon_illegal,
	kon_illegal,kon_ldd_ix ,kon_illegal,kon_ldx_ix ,kon_illegal,kon_ldy_ix ,kon_illegal,kon_ldu_ix  ,	/** 40 */
	kon_illegal,kon_lds_ix ,kon_illegal,kon_cmpd_ix,kon_illegal,kon_cmpx_ix,kon_illegal,kon_cmpy_ix,
	kon_illegal,kon_cmpu_ix,kon_illegal,kon_cmps_ix,kon_illegal,kon_addd_ix,kon_illegal,kon_subd_ix,	/* 50 */
	kon_std_ix ,kon_stx_ix ,kon_sty_ix ,kon_stu_ix ,kon_sts_ix ,kon_illegal,kon_illegal,kon_illegal,
	kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,	/* 60 */
	kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,
	kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,	/* 70 */
	kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,
	kon_illegal,kon_illegal,kon_clr_ix ,kon_illegal,kon_illegal,kon_com_ix ,kon_illegal,kon_illegal,	/* 80 */
	kon_neg_ix ,kon_illegal,kon_illegal,kon_inc_ix ,kon_illegal,kon_illegal,kon_dec_ix ,kon_illegal,
	kon_illegal,kon_illegal,kon_tst_ix ,kon_illegal,kon_illegal,kon_lsr_ix ,kon_illegal,kon_illegal,	/* 90 */
	kon_ror_ix ,kon_illegal,kon_illegal,kon_asr_ix ,kon_illegal,kon_illegal,kon_asl_ix ,kon_illegal,
	kon_illegal,kon_illegal,kon_rol_ix ,kon_lsrw_ix,kon_rorw_ix,kon_asrw_ix,kon_aslw_ix,kon_rolw_ix,	/* a0 */
	kon_jmp_ix ,kon_jsr_ix ,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,
	kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,	/* b0 */
	kon_illegal,kon_lsrd_ix,kon_illegal,kon_rord_ix,kon_illegal,kon_asrd_ix,kon_illegal,kon_asld_ix,
	kon_illegal,kon_rold_ix,kon_illegal,kon_clrw_ix,kon_illegal,kon_negw_ix,kon_illegal,kon_incw_ix,	/* c0 */
	kon_illegal,kon_decw_ix,kon_illegal,kon_tstw_ix,kon_illegal,kon_illegal,kon_illegal,kon_illegal,
	kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,	/* d0 */
	kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,
	kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,	/* e0 */
	kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,
	kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,	/* f0 */
	kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal
};

static void (*konami_direct[0x100])(void) = {
	kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,	/* 00 */
	kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,
	kon_illegal,kon_illegal,kon_lda_di ,kon_ldb_di ,kon_illegal,kon_illegal,kon_adda_di,kon_addb_di,	/* 10 */
	kon_illegal,kon_illegal,kon_adca_di,kon_adcb_di,kon_illegal,kon_illegal,kon_suba_di,kon_subb_di,
	kon_illegal,kon_illegal,kon_sbca_di,kon_sbcb_di,kon_illegal,kon_illegal,kon_anda_di,kon_andb_di,	/* 20 */
	kon_illegal,kon_illegal,kon_bita_di,kon_bitb_di,kon_illegal,kon_illegal,kon_eora_di,kon_eorb_di,
	kon_illegal,kon_illegal,kon_ora_di ,kon_orb_di ,kon_illegal,kon_illegal,kon_cmpa_di,kon_cmpb_di,	/* 30 */
	kon_illegal,kon_setline_di,kon_sta_di,kon_stb_di,kon_illegal,kon_illegal,kon_illegal,kon_illegal,
	kon_illegal,kon_ldd_di ,kon_illegal,kon_ldx_di ,kon_illegal,kon_ldy_di ,kon_illegal,kon_ldu_di  ,	/** 40 */
	kon_illegal,kon_lds_di ,kon_illegal,kon_cmpd_di,kon_illegal,kon_cmpx_di,kon_illegal,kon_cmpy_di,
	kon_illegal,kon_cmpu_di,kon_illegal,kon_cmps_di,kon_illegal,kon_addd_di,kon_illegal,kon_subd_di,	/* 50 */
	kon_std_di ,kon_stx_di ,kon_sty_di ,kon_stu_di ,kon_sts_di ,kon_illegal,kon_illegal,kon_illegal,
	kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,	/* 60 */
	kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,
	kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,	/* 70 */
	kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,
	kon_illegal,kon_illegal,kon_clr_di ,kon_illegal,kon_illegal,kon_com_di ,kon_illegal,kon_illegal,	/* 80 */
	kon_neg_di ,kon_illegal,kon_illegal,kon_inc_di ,kon_illegal,kon_illegal,kon_dec_di ,kon_illegal,
	kon_illegal,kon_illegal,kon_tst_di ,kon_illegal,kon_illegal,kon_lsr_di ,kon_illegal,kon_illegal,	/* 90 */
	kon_ror_di ,kon_illegal,kon_illegal,kon_asr_di ,kon_illegal,kon_illegal,kon_asl_di ,kon_illegal,
	kon_illegal,kon_illegal,kon_rol_di ,kon_lsrw_di,kon_rorw_di,kon_asrw_di,kon_aslw_di,kon_rolw_di,	/* a0 */
	kon_jmp_di ,kon_jsr_di ,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,
	kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,	/* b0 */
	kon_illegal,kon_lsrd_di,kon_illegal,kon_rord_di,kon_illegal,kon_asrd_di,kon_illegal,kon_asld_di,
	kon_illegal,kon_rold_di,kon_illegal,kon_clrw_di,kon_illegal,kon_negw_di,kon_illegal,kon_incw_di,	/* c0 */
	kon_illegal,kon_decw_di,kon_illegal,kon_tstw_di,kon_illegal,kon_illegal,kon_illegal,kon_illegal,
	kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,	/* d0 */
	kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,
	kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,	/* e0 */
	kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,
	kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,	/* f0 */
	kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal
};

static void (*konami_extended[0x100])(void) = {
	kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,	/* 00 */
	kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,
	kon_illegal,kon_illegal,kon_lda_ex ,kon_ldb_ex ,kon_illegal,kon_illegal,kon_adda_ex,kon_addb_ex,	/* 10 */
	kon_illegal,kon_illegal,kon_adca_ex,kon_adcb_ex,kon_illegal,kon_illegal,kon_suba_ex,kon_subb_ex,
	kon_illegal,kon_illegal,kon_sbca_ex,kon_sbcb_ex,kon_illegal,kon_illegal,kon_anda_ex,kon_andb_ex,	/* 20 */
	kon_illegal,kon_illegal,kon_bita_ex,kon_bitb_ex,kon_illegal,kon_illegal,kon_eora_ex,kon_eorb_ex,
	kon_illegal,kon_illegal,kon_ora_ex ,kon_orb_ex ,kon_illegal,kon_illegal,kon_cmpa_ex,kon_cmpb_ex,	/* 30 */
	kon_illegal,kon_setline_ex,kon_sta_ex,kon_stb_ex,kon_illegal,kon_illegal,kon_illegal,kon_illegal,
	kon_illegal,kon_ldd_ex ,kon_illegal,kon_ldx_ex ,kon_illegal,kon_ldy_ex ,kon_illegal,kon_ldu_ex  ,	/** 40 */
	kon_illegal,kon_lds_ex ,kon_illegal,kon_cmpd_ex,kon_illegal,kon_cmpx_ex,kon_illegal,kon_cmpy_ex,
	kon_illegal,kon_cmpu_ex,kon_illegal,kon_cmps_ex,kon_illegal,kon_addd_ex,kon_illegal,kon_subd_ex,	/* 50 */
	kon_std_ex ,kon_stx_ex ,kon_sty_ex ,kon_stu_ex ,kon_sts_ex ,kon_illegal,kon_illegal,kon_illegal,
	kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,	/* 60 */
	kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,
	kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,	/* 70 */
	kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,
	kon_illegal,kon_illegal,kon_clr_ex ,kon_illegal,kon_illegal,kon_com_ex ,kon_illegal,kon_illegal,	/* 80 */
	kon_neg_ex ,kon_illegal,kon_illegal,kon_inc_ex ,kon_illegal,kon_illegal,kon_dec_ex ,kon_illegal,
	kon_illegal,kon_illegal,kon_tst_ex ,kon_illegal,kon_illegal,kon_lsr_ex ,kon_illegal,kon_illegal,	/* 90 */
	kon_ror_ex ,kon_illegal,kon_illegal,kon_asr_ex ,kon_illegal,kon_illegal,kon_asl_ex ,kon_illegal,
	kon_illegal,kon_illegal,kon_rol_ex ,kon_lsrw_ex,kon_rorw_ex,kon_asrw_ex,kon_aslw_ex,kon_rolw_ex,	/* a0 */
	kon_jmp_ex ,kon_jsr_ex ,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,
	kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,	/* b0 */
	kon_illegal,kon_lsrd_ex,kon_illegal,kon_rord_ex,kon_illegal,kon_asrd_ex,kon_illegal,kon_asld_ex,
	kon_illegal,kon_rold_ex,kon_illegal,kon_clrw_ex,kon_illegal,kon_negw_ex,kon_illegal,kon_incw_ex,	/* c0 */
	kon_illegal,kon_decw_ex,kon_illegal,kon_tstw_ex,kon_illegal,kon_illegal,kon_illegal,kon_illegal,
	kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,	/* d0 */
	kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,
	kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,	/* e0 */
	kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,
	kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,	/* f0 */
	kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal,kon_illegal
};
